# 生产环境配置

# API测试配置
api:
  base_url: http://api.example.com  # 生产环境API基础URL
  timeout: 20  # 生产环境请求超时时间(秒)
  headers:
    X-Environment: production

# UI测试配置
ui:
  base_url: http://ui.example.com  # 生产环境UI基础URL
  browser: chrome
  headless: true  # 生产环境使用无头模式
  timeout: 20

# SSH测试配置
ssh:
  default_servers:
    - name: prod-server-1
      host: prod-server-1.example.com
      port: 22
      username: prod_user
      key_file: ~/.ssh/prod_key  # 生产环境只使用密钥认证

# 并行执行配置
parallel:
  api: 5  # 生产环境API测试并行数
  ui: 3  # 生产环境UI测试并行数
  ssh: 3  # 生产环境SSH测试并行数

# 日志配置
log:
  level: WARNING  # 生产环境使用WARNING级别，减少日志量 