# 测试环境配置

# API测试配置
api:
  base_url: http://localhost:5000  # 修改为本地地址
  timeout: 15  # 测试环境请求超时时间(秒)
  headers:
    X-Environment: testing

# UI测试配置
ui:
  base_url: http://localhost:5000  # 修改为本地地址
  browser: chrome
  headless: true  # 测试环境使用无头模式
  timeout: 15

# SSH测试配置
ssh:
  default_servers:
    - name: localhost
      host: 127.0.0.1
      port: 22
      username: test_user
      password: test_password  # 注意：实际使用中应使用密钥认证或环境变量
    - name: test-server-2
      host: test-server-2.example.com
      port: 22
      username: test_user
      key_file: ~/.ssh/test_key

# 并行执行配置
parallel:
  api: 3  # 测试环境API测试并行数
  ui: 2  # 测试环境UI测试并行数
  ssh: 2  # 测试环境SSH测试并行数

# 日志配置
log:
  level: INFO  # 测试环境使用INFO级别 